"""Initial schema: requests, responses, immobili, intestati

Revision ID: 31f03df3db46
Revises: 
Create Date: 2026-04-11 08:32:20.970963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31f03df3db46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immobili',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_catasto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('foglio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('particella', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subalterno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indirizzo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('partita', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consistenza', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rendita', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zona_censuaria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qualita', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('superficie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reddito_dominicale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reddito_agrario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('denominazione', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sede', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('codice_fiscale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provincia_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comune_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['visura_responses.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('immobili', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immobili_codice_fiscale'), ['codice_fiscale'], unique=False)
        batch_op.create_index(batch_op.f('ix_immobili_response_id'), ['response_id'], unique=False)

    op.create_table('intestati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nominativo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('codice_fiscale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('titolarita', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quota', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['visura_responses.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intestati', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intestati_codice_fiscale'), ['codice_fiscale'], unique=False)
        batch_op.create_index(batch_op.f('ix_intestati_response_id'), ['response_id'], unique=False)

    with op.batch_alter_table('visura_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('request_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('request_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('tipo_catasto',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('provincia',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('comune',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('foglio',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('particella',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('sezione',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('subalterno',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%f', 'now', 'localtime'))"))
        batch_op.drop_index(batch_op.f('idx_requests_created_at'))
        batch_op.create_index(batch_op.f('ix_visura_requests_cache_key'), ['cache_key'], unique=False)

    with op.batch_alter_table('visura_responses', schema=None) as batch_op:
        batch_op.alter_column('request_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('success',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('tipo_catasto',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('error',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%f', 'now', 'localtime'))"))
        batch_op.drop_index(batch_op.f('idx_responses_created_at'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visura_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_responses_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%f', 'now', 'localtime'))"))
        batch_op.alter_column('error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo_catasto',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('success',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('request_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('visura_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visura_requests_cache_key'))
        batch_op.create_index(batch_op.f('idx_requests_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%f', 'now', 'localtime'))"))
        batch_op.alter_column('subalterno',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sezione',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('particella',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('foglio',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('comune',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('provincia',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('tipo_catasto',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('request_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('request_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('cache_key')

    with op.batch_alter_table('intestati', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intestati_response_id'))
        batch_op.drop_index(batch_op.f('ix_intestati_codice_fiscale'))

    op.drop_table('intestati')
    with op.batch_alter_table('immobili', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immobili_response_id'))
        batch_op.drop_index(batch_op.f('ix_immobili_codice_fiscale'))

    op.drop_table('immobili')
    # ### end Alembic commands ###
